spring:
    datasource:
        url: jdbc:mysql://localhost:3306/sample
        username: sa
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver

    flyway:
        enabled: true
        create-schemas: true
        url: ${spring.datasource.url}
        user: ${spring.datasource.username}
        password: ${spring.datasource.password}
        locations: classpath:db/migration
